# Setup
title:               Taming Code
# tagline:             ''
description:         'Reflections about code authored by <a href="https://twitter.com/filpen" target="_blank">Filippo Pensalfini</a>.'
url:                 http://tamingcode.com
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Filippo Pensalfini
  url:               https://twitter.com/filpen
  email:             firstname.lastname@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: UA-34450259-1
